env:
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
rules:
  no-console: 2
  prefer-const: 2
  no-var: 2
  no-param-reassign: 2
  array-callback-return: 2
  import/no-extraneous-dependencies: 2
  import/order:
    - error
    - newlines-between: always-and-inside-groups
  prettier/prettier: error

plugins:
  - jest
  - prettier
  - import
